services:
  backend:
    image: '${DOCKER_IMAGE_BACKEND?Variable not set}:${TAG-latest}'
    env_file:
      - .env
    environment:
      - PROJECT_NAME=${PROJECT_NAME?Variable not set}
      - MYSQL_USER=${MYSQL_USER?Variable not set}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD?Variable not set}
      - MYSQL_HOST=${MYSQL_HOST?Variable not set}
      - MYSQL_PORT=${MYSQL_PORT?Variable not set}
      - MYSQL_DB=${MYSQL_DB?Variable not set}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health-check"]
      interval: 10s
      timeout: 5s
      retries: 5
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"

  frontend:
    image: '${DOCKER_IMAGE_FRONTEND?Variable not set}:${TAG-latest}'
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL?Variable not set}
    ports:
      - "5173:80"
